# Generated by:
#
#     mix ichor.gen priv/grammar/casc_interp.aether --module Cooper.NativeInterpGrammar.Native --actions Cooper.InterpActions --out lib/cooper/native_interp_grammar/native.ex
#
# Do not edit by hand -- rerun the command above instead.
defmodule Cooper.NativeInterpGrammar.Native do
  @moduledoc false
  (
    @dialyzer [:no_opaque, :no_match]
    alias Grammar.Native.Runtime.{Parser, Tokenizer}
    alias Grammar.VM.Token

    def lex_token__DIGIT(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__ALPHA(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 122}, {65, 90}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_expr__0(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_expr__1(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 122}, {65, 90}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__ALNUM(input) do
      Tokenizer.first_char_match([&lex_expr__0/1, &lex_expr__1/1], input)
    end

    def lex_token__SPACE(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{32, 32}, {9, 9}, {13, 13}, {10, 10}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_token__HEX(input) do
      case input do
        <<c::utf8, rest::binary>> ->
          if Tokenizer.in_ranges?(c, [{97, 102}, {65, 70}, {48, 57}]) do
            {:ok, <<c::utf8>>, rest}
          else
            :fail
          end

        _ ->
          :fail
      end
    end

    def lex_expr__2(input) do
      case input do
        <<"@{", rest::binary>> -> {:ok, "@{", rest}
        _ -> :fail
      end
    end

    def lex_expr__6(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_expr__5(input) do
      Tokenizer.not_pred_char(&lex_expr__6/1, input)
    end

    def lex_expr__7(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_expr__4(input0) do
      with {:ok, t0, rest0} <- lex_expr__5(input0), {:ok, t1, rest1} <- lex_expr__7(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_expr__3(input) do
      Tokenizer.star_char(&lex_expr__4/1, input)
    end

    def lex_expr__8(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_token__AT_REF_RAW(input0) do
      with {:ok, t0, rest0} <- lex_expr__2(input0),
           {:ok, t1, rest1} <- lex_expr__3(rest0),
           {:ok, t2, rest2} <- lex_expr__8(rest1) do
        {:ok, t0 <> t1 <> t2, rest2}
      else
        :fail -> :fail
      end
    end

    def lex_expr__9(input) do
      case input do
        <<"${", rest::binary>> -> {:ok, "${", rest}
        _ -> :fail
      end
    end

    def lex_expr__13(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_expr__12(input) do
      Tokenizer.not_pred_char(&lex_expr__13/1, input)
    end

    def lex_expr__14(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_expr__11(input0) do
      with {:ok, t0, rest0} <- lex_expr__12(input0), {:ok, t1, rest1} <- lex_expr__14(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_expr__10(input) do
      Tokenizer.star_char(&lex_expr__11/1, input)
    end

    def lex_expr__15(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_token__ENV_REF_RAW(input0) do
      with {:ok, t0, rest0} <- lex_expr__9(input0),
           {:ok, t1, rest1} <- lex_expr__10(rest0),
           {:ok, t2, rest2} <- lex_expr__15(rest1) do
        {:ok, t0 <> t1 <> t2, rest2}
      else
        :fail -> :fail
      end
    end

    def lex_expr__16(input) do
      case input do
        <<"%{", rest::binary>> -> {:ok, "%{", rest}
        _ -> :fail
      end
    end

    def lex_expr__20(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_expr__19(input) do
      Tokenizer.not_pred_char(&lex_expr__20/1, input)
    end

    def lex_expr__21(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_expr__18(input0) do
      with {:ok, t0, rest0} <- lex_expr__19(input0), {:ok, t1, rest1} <- lex_expr__21(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_expr__17(input) do
      Tokenizer.star_char(&lex_expr__18/1, input)
    end

    def lex_expr__22(input) do
      case input do
        <<"}", rest::binary>> -> {:ok, "}", rest}
        _ -> :fail
      end
    end

    def lex_token__CONFIG_REF_RAW(input0) do
      with {:ok, t0, rest0} <- lex_expr__16(input0),
           {:ok, t1, rest1} <- lex_expr__17(rest0),
           {:ok, t2, rest2} <- lex_expr__22(rest1) do
        {:ok, t0 <> t1 <> t2, rest2}
      else
        :fail -> :fail
      end
    end

    def lex_expr__23(input) do
      lex_token__ALPHA(input)
    end

    def lex_expr__26(input) do
      lex_token__ALNUM(input)
    end

    def lex_expr__27(input) do
      case input do
        <<"_", rest::binary>> -> {:ok, "_", rest}
        _ -> :fail
      end
    end

    def lex_expr__28(input) do
      case input do
        <<"+", rest::binary>> -> {:ok, "+", rest}
        _ -> :fail
      end
    end

    def lex_expr__29(input) do
      case input do
        <<"-", rest::binary>> -> {:ok, "-", rest}
        _ -> :fail
      end
    end

    def lex_expr__25(input) do
      Tokenizer.first_char_match(
        [&lex_expr__26/1, &lex_expr__27/1, &lex_expr__28/1, &lex_expr__29/1],
        input
      )
    end

    def lex_expr__24(input) do
      Tokenizer.star_char(&lex_expr__25/1, input)
    end

    def lex_expr__32(input) do
      case input do
        <<"?", rest::binary>> -> {:ok, "?", rest}
        _ -> :fail
      end
    end

    def lex_expr__33(input) do
      case input do
        <<"!", rest::binary>> -> {:ok, "!", rest}
        _ -> :fail
      end
    end

    def lex_expr__31(input) do
      Tokenizer.first_char_match([&lex_expr__32/1, &lex_expr__33/1], input)
    end

    def lex_expr__30(input) do
      Tokenizer.opt_char(&lex_expr__31/1, input)
    end

    def lex_token__TAG_NAME(input0) do
      with {:ok, t0, rest0} <- lex_expr__23(input0),
           {:ok, t1, rest1} <- lex_expr__24(rest0),
           {:ok, t2, rest2} <- lex_expr__30(rest1) do
        {:ok, t0 <> t1 <> t2, rest2}
      else
        :fail -> :fail
      end
    end

    def lex_expr__34(input) do
      case input do
        <<"!", rest::binary>> -> {:ok, "!", rest}
        _ -> :fail
      end
    end

    def lex_expr__35(input) do
      lex_token__TAG_NAME(input)
    end

    def lex_expr__36(input) do
      case input do
        <<"(", rest::binary>> -> {:ok, "(", rest}
        _ -> :fail
      end
    end

    def lex_expr__40(input) do
      case input do
        <<")", rest::binary>> -> {:ok, ")", rest}
        _ -> :fail
      end
    end

    def lex_expr__39(input) do
      Tokenizer.not_pred_char(&lex_expr__40/1, input)
    end

    def lex_expr__41(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_expr__38(input0) do
      with {:ok, t0, rest0} <- lex_expr__39(input0), {:ok, t1, rest1} <- lex_expr__41(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_expr__37(input) do
      Tokenizer.star_char(&lex_expr__38/1, input)
    end

    def lex_expr__42(input) do
      case input do
        <<")", rest::binary>> -> {:ok, ")", rest}
        _ -> :fail
      end
    end

    def lex_token__TAGGED_REF_RAW(input0) do
      with {:ok, t0, rest0} <- lex_expr__34(input0),
           {:ok, t1, rest1} <- lex_expr__35(rest0),
           {:ok, t2, rest2} <- lex_expr__36(rest1),
           {:ok, t3, rest3} <- lex_expr__37(rest2),
           {:ok, t4, rest4} <- lex_expr__42(rest3) do
        {:ok, t0 <> t1 <> t2 <> t3 <> t4, rest4}
      else
        :fail -> :fail
      end
    end

    def lex_expr__43(input) do
      case input do
        <<"!", rest::binary>> -> {:ok, "!", rest}
        _ -> :fail
      end
    end

    def lex_expr__44(input) do
      lex_token__TAG_NAME(input)
    end

    def lex_expr__45(input) do
      case input do
        <<"(", rest::binary>> -> {:ok, "(", rest}
        _ -> :fail
      end
    end

    def lex_token__BANG_TAG(input0) do
      with {:ok, t0, rest0} <- lex_expr__43(input0),
           {:ok, t1, rest1} <- lex_expr__44(rest0),
           {:ok, t2, rest2} <- lex_expr__45(rest1) do
        {:ok, t0 <> t1 <> t2, rest2}
      else
        :fail -> :fail
      end
    end

    def lex_expr__49(input) do
      case input do
        <<"@{", rest::binary>> -> {:ok, "@{", rest}
        _ -> :fail
      end
    end

    def lex_expr__50(input) do
      case input do
        <<"${", rest::binary>> -> {:ok, "${", rest}
        _ -> :fail
      end
    end

    def lex_expr__51(input) do
      case input do
        <<"%{", rest::binary>> -> {:ok, "%{", rest}
        _ -> :fail
      end
    end

    def lex_expr__52(input) do
      case input do
        <<"!{", rest::binary>> -> {:ok, "!{", rest}
        _ -> :fail
      end
    end

    def lex_expr__53(input) do
      lex_token__BANG_TAG(input)
    end

    def lex_expr__48(input) do
      Tokenizer.first_char_match(
        [&lex_expr__49/1, &lex_expr__50/1, &lex_expr__51/1, &lex_expr__52/1, &lex_expr__53/1],
        input
      )
    end

    def lex_expr__47(input) do
      Tokenizer.not_pred_char(&lex_expr__48/1, input)
    end

    def lex_expr__54(input) do
      case input do
        <<c::utf8, rest::binary>> -> {:ok, <<c::utf8>>, rest}
        _ -> :fail
      end
    end

    def lex_expr__46(input0) do
      with {:ok, t0, rest0} <- lex_expr__47(input0), {:ok, t1, rest1} <- lex_expr__54(rest0) do
        {:ok, t0 <> t1, rest1}
      else
        :fail -> :fail
      end
    end

    def lex_token__TEXT_CHUNK(input) do
      Tokenizer.plus_char(&lex_expr__46/1, input)
    end

    def lex_candidates(input, context) do
      [
        AT_REF_RAW: fn ->
          case lex_token__AT_REF_RAW(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        ENV_REF_RAW: fn ->
          case lex_token__ENV_REF_RAW(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        CONFIG_REF_RAW: fn ->
          case lex_token__CONFIG_REF_RAW(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        RESOLVER_REF_RAW: fn ->
          rule_matchers = Map.new([])

          case apply(Cooper.Native.ResolverRef, :scan, [input, context, rule_matchers]) do
            {:ok, text, rest, capture} -> {:ok, text, rest, capture}
            :fail -> :fail
          end
        end,
        TAGGED_REF_RAW: fn ->
          case lex_token__TAGGED_REF_RAW(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end,
        TEXT_CHUNK: fn ->
          case lex_token__TEXT_CHUNK(input) do
            {:ok, text, rest} -> {:ok, text, rest, nil}
            :fail -> :fail
          end
        end
      ]
    end

    def parse_expr__0(stream, pos, ref_stack, context) do
      case parse_rule__segment(stream, pos, ref_stack, context) do
        {:ok, new_pos, new_ref_stack, sub_captures} ->
          {:ok, new_pos, new_ref_stack, segment: {:rule, :segment, sub_captures}}

        _fail ->
          :fail
      end
    end

    def parse_rule__text(stream, pos, ref_stack, context) do
      Parser.star(&parse_expr__0/4, stream, pos, ref_stack, context)
    end

    def parse_expr__1(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :AT_REF_RAW) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, AT_REF_RAW: {:token, :AT_REF_RAW, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, AT_REF_RAW: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__2(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :ENV_REF_RAW) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, ENV_REF_RAW: {:token, :ENV_REF_RAW, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, ENV_REF_RAW: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__3(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :CONFIG_REF_RAW) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, CONFIG_REF_RAW: {:token, :CONFIG_REF_RAW, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, CONFIG_REF_RAW: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__4(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :RESOLVER_REF_RAW) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, RESOLVER_REF_RAW: {:token, :RESOLVER_REF_RAW, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, RESOLVER_REF_RAW: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__5(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :TAGGED_REF_RAW) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, TAGGED_REF_RAW: {:token, :TAGGED_REF_RAW, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, TAGGED_REF_RAW: capture}

        :fail ->
          :fail
      end
    end

    def parse_expr__6(stream, pos, ref_stack, _context) do
      case Parser.match_token(stream, pos, :TEXT_CHUNK) do
        {:ok, new_pos, text, nil} ->
          {:ok, new_pos, ref_stack, TEXT_CHUNK: {:token, :TEXT_CHUNK, text}}

        {:ok, new_pos, _text, capture} ->
          {:ok, new_pos, ref_stack, TEXT_CHUNK: capture}

        :fail ->
          :fail
      end
    end

    def parse_rule__segment(stream, pos, ref_stack, context) do
      Parser.try_alts(
        [
          &parse_expr__1/4,
          &parse_expr__2/4,
          &parse_expr__3/4,
          &parse_expr__4/4,
          &parse_expr__5/4,
          &parse_expr__6/4
        ],
        stream,
        pos,
        ref_stack,
        context
      )
    end

    (
      @doc "Tokenizes `input` completely via maximal munch, applies any `@keywords`/`@refine` rules, or reports the first position nothing matches. `context` is read-only and only ever consulted by a `Grammar.IR.CustomLexeme` `@native(...)` token, if the grammar has one."
      @spec tokenize(String.t(), term()) :: {:ok, [Token.t()]} | {:error, Ichor.Error.t()}
      def tokenize(input, context \\ nil) do
        with {:ok, input} <- Grammar.Source.validate(input),
             {:ok, raw_tokens} <-
               Tokenizer.tokenize(fn inp -> lex_candidates(inp, context) end, input) do
          Grammar.Lexer.reclassify(raw_tokens, %{})
        end
      end
    )

    @doc "Matches `input` against the grammar's root rule, requiring the entire (tokenized) input to be consumed. A bare recognizer -- no `Ichor.Actions` involved. `context` is read-only and only ever consulted by a `Grammar.IR.Custom` `@native(...)` node, if the grammar has one."
    @spec parse(String.t(), term()) ::
            {:ok, non_neg_integer(), Ichor.Capture.raw_captures()} | {:error, Ichor.Error.t()}
    def parse(input, context \\ nil) do
      with {:ok, tokens} <- tokenize(input, context) do
        stream = List.to_tuple(tokens)

        case parse_rule__text(stream, 0, [0], context) do
          {:ok, pos, _ref_stack, raw_captures} when pos == tuple_size(stream) ->
            {:ok, pos, raw_captures}

          {:ok, pos, _ref_stack, _raw_captures} ->
            {:error, Parser.unexpected_token_error(stream, pos, input)}

          _fail ->
            {:error,
             Ichor.Error.new(
               message: "input does not match #{inspect(:text)}",
               stage: :parser,
               source: input
             )}
        end
      end
    end

    @doc "Like `parse/1`, but runs the match through the compile-time-known Actions module, returning the grammar's actual evaluated result."
    @spec run(String.t(), Ichor.Actions.context()) ::
            {:ok, term()} | {:error, Ichor.Error.t() | [Ichor.Error.t()]}
    def run(input, initial_context \\ nil) do
      with {:ok, _pos, raw_captures} <- parse(input, initial_context),
           {:ok, value, _context} <-
             Ichor.Actions.evaluate(:text, raw_captures, Cooper.InterpActions, initial_context, %{
               text: MapSet.new([:segment]),
               segment: MapSet.new([])
             }) do
        {:ok, value}
      end
    end

    @doc "Like `run/2`, but evaluates `input` as a sequence of top-level matches against the root rule, one after another, threading context from each into the next (loading a standard-library file one top-level form at a time is the motivating case -- most grammars only ever need `run/2`)."
    @spec run_sequence(String.t(), Ichor.Actions.context()) ::
            {:ok, [term()], Ichor.Actions.context()}
            | {:error, Ichor.Error.t() | [Ichor.Error.t()]}
    def run_sequence(input, initial_context) do
      with {:ok, tokens} <- tokenize(input, initial_context) do
        do_run_sequence(List.to_tuple(tokens), 0, initial_context, [])
      end
    end

    def do_run_sequence(stream, pos, ctx, acc) do
      pos = Parser.skip_leading_trivia(stream, pos, nil)

      if pos >= tuple_size(stream) do
        {:ok, Enum.reverse(acc), ctx}
      else
        case parse_rule__text(stream, pos, [0], ctx) do
          {:ok, new_pos, _ref_stack, raw_captures} ->
            case Ichor.Actions.evaluate(:text, raw_captures, Cooper.InterpActions, ctx, %{
                   text: MapSet.new([:segment]),
                   segment: MapSet.new([])
                 }) do
              {:ok, value, new_ctx} -> do_run_sequence(stream, new_pos, new_ctx, [value | acc])
              {:error, _} = err -> err
            end

          _fail ->
            {:error,
             Ichor.Error.new(message: "input does not match #{inspect(:text)}", stage: :parser)}
        end
      end
    end
  )
end
