# Generated by:
#
#     mix run scripts/gen_capture_shapes.exs
#
# Do not edit by hand -- rerun the command above instead.
defmodule Cooper.NativeGrammar.CaptureShapes do
  @moduledoc false
  (
    @doc "Which of each rule's own named captures are repeatable (behind a `*`/`+`/`{n,}`/... quantifier, so `Ichor.Actions` should normalize that name's raw capture into a list even when it matched only once or zero times) -- `Grammar.VM.RuleCompiler.capture_shapes/1`'s output for `casc.aether`, computed ahead of time by `scripts/gen_capture_shapes.exs` rather than at runtime."
    @spec get() :: Ichor.Actions.capture_shapes()
    def get do
      %{
        at_ref: MapSet.new([]),
        atom_value: MapSet.new([]),
        atom_word: MapSet.new([]),
        binding: MapSet.new([]),
        block: MapSet.new([:statement]),
        colon_atom: MapSet.new([]),
        conditional_statement: MapSet.new([]),
        config_ref: MapSet.new([]),
        delete_statement: MapSet.new([]),
        disabled_statement: MapSet.new([]),
        env_bracket: MapSet.new([]),
        env_guard: MapSet.new([]),
        env_ref: MapSet.new([]),
        file: MapSet.new([:statement]),
        filter: MapSet.new([]),
        filter_arg: MapSet.new([]),
        filters: MapSet.new([:filter]),
        for_statement: MapSet.new([:binding]),
        idx_suffix: MapSet.new([]),
        import_path: MapSet.new([]),
        import_statement: MapSet.new([]),
        iterable_value: MapSet.new([]),
        key_path: MapSet.new([:key_segment]),
        key_segment: MapSet.new([]),
        list: MapSet.new([:value]),
        real_statement: MapSet.new([]),
        ref_suffix: MapSet.new([]),
        resolver_ref: MapSet.new([]),
        rhs: MapSet.new([]),
        seg: MapSet.new([]),
        sigil_kv_statement: MapSet.new([]),
        statement: MapSet.new([]),
        tagged_ref: MapSet.new([]),
        tuple: MapSet.new([:value]),
        value: MapSet.new([]),
        var_decl: MapSet.new([]),
        version_head: MapSet.new([]),
        version_header: MapSet.new([]),
        version_number: MapSet.new([:n])
      }
    end
  )
end
