# Generates lib/cooper/native_grammar/capture_shapes.ex -- a plain data
# literal, checked in like any other source file, exactly the same
# "compute once ahead of time instead of at every consumer's runtime"
# idea `mix ichor.gen` applies to the parser itself.
#
# Why this needs its own script rather than being covered by `mix
# ichor.gen`: `Cooper.Grammar.run_with_context/3` calls
# `Ichor.Actions.evaluate/5` directly (not the generated `run/2`) so it
# gets the final `Ichor.Actions.context()` back -- `Cooper.Loader` needs
# a file's accumulated `ctx.vars` for cross-file variable propagation,
# and the generated `run/2`/`run_sequence/2` either discard it or don't
# fit this grammar's single-root-match shape (see
# `Cooper.NativeGrammar`'s own moduledoc). `evaluate/5` needs
# `capture_shapes` (`Grammar.VM.RuleCompiler.capture_shapes/1`) as its
# last argument -- `Grammar.Native.generate/2` already computes the
# identical value at codegen time and bakes it into `run/2`/
# `run_sequence/2` as a literal, but doesn't expose it as its own
# callable; this script computes that same value the same way and
# checks it in separately, so `Cooper.Grammar` never needs
# `Grammar.VM.RuleCompiler` (part of `ichor` proper, dev/test-only) at
# runtime either.
#
# Run whenever priv/grammar/casc.aether changes (alongside the
# `mix ichor.gen` command in `Cooper.NativeGrammar`'s own moduledoc):
#
#     mix run scripts/gen_capture_shapes.exs

grammar_path = "priv/grammar/casc.aether"
out_path = "lib/cooper/native_grammar/capture_shapes.ex"
module = Cooper.NativeGrammar.CaptureShapes

source = File.read!(grammar_path)
{:ok, grammar} = Aether.Parser.parse(source, grammar_path)
{:ok, grammar} = Grammar.Analysis.run(grammar)
shapes = Grammar.VM.RuleCompiler.capture_shapes(grammar)

# Reconstructed as `%{rule => MapSet.new([...])}` calls rather than
# `Macro.escape/1`'s raw `%{__struct__: MapSet, map: %{...}}` form --
# functionally identical, but readable in the checked-in file and not
# tied to MapSet's own internal representation.
shape_entries =
  for {rule, set} <- Enum.sort_by(shapes, &elem(&1, 0)) do
    repeatable_names = set |> MapSet.to_list() |> Enum.sort()
    {rule, quote(do: MapSet.new(unquote(repeatable_names)))}
  end

doc =
  "Which of each rule's own named captures are repeatable (behind a `*`/`+`/`{n,}`/... " <>
    "quantifier, so `Ichor.Actions` should normalize that name's raw capture into a list " <>
    "even when it matched only once or zero times) -- `Grammar.VM.RuleCompiler.capture_shapes/1`'s " <>
    "output for `casc.aether`, computed ahead of time by `scripts/gen_capture_shapes.exs` rather than at runtime."

body =
  quote do
    @doc unquote(doc)
    @spec get() :: Ichor.Actions.capture_shapes()
    def get, do: %{unquote_splicing(shape_entries)}
  end

text =
  quote do
    defmodule unquote(module) do
      @moduledoc false
      unquote(body)
    end
  end
  |> Macro.to_string()
  |> Code.format_string!()
  |> IO.iodata_to_binary()

banner = """
# Generated by:
#
#     mix run scripts/gen_capture_shapes.exs
#
# Do not edit by hand -- rerun the command above instead.
"""

File.write!(out_path, banner <> text <> "\n")
IO.puts("* creating #{out_path}")
